#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

#bspc monitor -d 1 2 3 4 5 6 7 8 9 10
bspc monitor -d 8 9 0 7 6 5 4

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

#bspc rule -a Gimp desktop='^8' state=floating follow=on
#bspc rule -a mplayer2 state=floating
#bspc rule -a Kupfer.py focus=on
#bspc rule -a Screenkey manage=off
bspc rule -a Zathura state=tiled

polybar mybar &
